### ISSUE TITLE
Input: onChange instead of onBlur

### ISSUE THREAD

**Issue by markronquillo** [denisraslov/react-spreadsheet-grid#13]
With the current change in `Input` component, I think the documentation should also be updated. 

Using `onBlur` to capture `Input` changes doesn't work now, it works if we use onChange props.

I can make a PR if you want.

**Comment by denisraslov** [comment]
Hello @markronquillo 

Thank you!
Right, documentation should be updated as you said. I missed this thing in the last release 😟
The PR will be very welcome!

**Comment by denisraslov** [comment]
Fixed in the **release 1.3.1** 🙂
