### ISSUE TITLE
Add new rows/columns

### ISSUE THREAD

**Issue by vaibhavviswanathan** [denisraslov/react-spreadsheet-grid#14]
Is it possible to add new rows or columns? 

If so, how?

THanks!

**Comment by denisraslov** [comment]
It's absolutely possible. You should store columns and rows in the state of parent component, so you can call `setState` with updated columns or rows to render a grid with them.
For example, see how you can put new rows in a grid in [this section of the docs](https://github.com/denisraslov/react-spreadsheet-grid#lazy-loading-support).
