### ISSUE TITLE
collaboration friendly

### ISSUE THREAD

**Issue by evanoralph** [denisraslov/react-spreadsheet-grid#16]
is there a chance that I can use this in a collaboration app?

**Comment by denisraslov** [comment]
Hi @evanoralph 
Yes! I think there are no problems with using this component in a collaboration app. Do you see any?

**Comment by evanoralph** [comment]
nothing just confuse in your example demo you can resize the col but mine is not im not sure, is this compatible with react 16.2.0?

**Comment by denisraslov** [comment]
Yes, it is compatible with React 16.2.0.
Can you show the props that you pass to the grid? You have to set `isColumnsResizable` in true to get resizable columns.
