### ISSUE TITLE
Display "there are no rows" even if there are

### ISSUE THREAD

**Issue by acailly** [denisraslov/react-spreadsheet-grid#23]
* `react-spreadsheet-grid` version: 1.4.3
* `React` version: 16.4.1
* `Operating System`: Windows 7 64 bits

## Reproducible example

https://codesandbox.io/s/9z87w6vk34

When grid is empty, click on BUG button : "there are no rows" is displayed even if there is 1 row

Then click on the scroll arrow : magic! Row appears

## Intent

I have a Grid that gets updated when redux state is updated.

When the page is loaded, redux state is empty then the grid is updated with no rows a couple times then redux state is filled so the grid is updated with some data

## Issue

The grid is not refreshed when updated with some data, so the message "there are no rows" stays

## Analysis

I think this is what is happenning: 
- Grid is updated with no rows a couple times, `SpreadsheetGridScrollWrapper.calculateScrollState` is triggered and `SpreadsheetGridScrollWrapper.state.last` is set to 0 
- Grid is updated with some data, `SpreadsheetGridScrollWrapper.calculateScrollState` is triggered so that `SpreadsheetGridScrollWrapper.state.last` is updated...
- ... but `SpreadsheetGridScrollWrapper.calculateScrollState` is throttled with `requestAnimationFrame` (`scrollWrapper/index.js:31`) so it is not executed before the grid render and...
- ... when the grid renders `SpreadsheetGridScrollWrapper.state.last` is still equal to 0 so `Grid` takes the element from 0 to 0, that means nothing, that's why "there are no rows" is displayed even if `this.props.rows` contains some data

## Fix

I really don't know :disappointed: 

The only workaround I found is to encaspulate the state update in `requestAnimationFrame` but I have the feeling that it can cause more bugs: https://codesandbox.io/s/9qy425m30o

**Comment by acailly** [comment]
I found another workaround, setting the Grid key to the rows length makes the Grid full render when the rows length changes: https://codesandbox.io/s/v07k08qx9l.
(but it throw an error in the console)

**Comment by denisraslov** [comment]
Hi @acailly 
Seems the bug was fixed in version 2. 
Please, take a look.
