### ISSUE TITLE
Is there a scrollX option in addition to scrollY?

### ISSUE THREAD

**Issue by pstephenwille** [denisraslov/react-spreadsheet-grid#25]
* `react-spreadsheet-grid` version:
* `React` version:
* `Operating System`:

Relevant code or config

```javascript
```

What you did:

What happened:

Problem description:

Suggested solution:

**Comment by denisraslov** [comment]
Hi @pstephenwille!

What do you mean by scrollX option?

**Comment by denisraslov** [comment]
Hi @pstephenwille 
If you mean an opportunity to get a horizontally scrollable grid, the second part of this commentary would be useful for you:
https://github.com/denisraslov/react-spreadsheet-grid/issues/28#issuecomment-575930853
