### ISSUE TITLE
Make column widths correspond to contents

### ISSUE THREAD

**Issue by avalanche1** [denisraslov/react-spreadsheet-grid#28]
I have a rather wide table with many columns. I don't want them all squeezed inside the viewport. Instead I'd like column widths to fit column content and have a horizontal scrollbar to scroll to the columns that are offscreen.
Is that possible?

**Comment by kasbah** [comment]
I think this can be a hard problem to solve for everyone's use case. As you probably figured out you can calculate the desired widths yourself and pass them to react-spreadsheet-grid. 

Adding a horizontal scrollbar is another matter. As it stands I believe react-spreadsheet-grid will always try to fit into the available vertical space and never scroll.

**Comment by kasbah** [comment]
Although, after experimenting a bit. There doesn't seem any way to change the column width programmatically after the first render?

**Comment by denisraslov** [comment]
Yes, @kasbah is right here:

> I think this can be a hard problem to solve for everyone's use case. As you probably figured out you can calculate the desired widths yourself and pass them to react-spreadsheet-grid.

Initially, `react-spreadsheet-grid` makes all the columns to have the same width, but it's better to decide which widths you want columns to be and pass it as `columnWidthValues` prop.
It also could be not the best solution to make a column's width fit its content. What should be done if the content is a long string? It would fill 99% of the grid's width then.

What about horizontal scrollbar, you can actually implement it. Just make a horizontally scrollable container with desirable width and put the grid into this. Something like this:
```javascript
<div style={{ 'overflow-x': 'auto', width: '100%' }}>
   <div style={{ width: '1000px' }}>
      <Grid />
   </div>
</div>
```

**Comment by denisraslov** [comment]
> Although, after experimenting a bit, there doesn't seem any way to change the column width programmatically after the first render?

You can change the column's widths by passing a new object to the `columnWidthValues` prop 🙂
