### ISSUE TITLE
Feature request: height property

### ISSUE THREAD

**Issue by kasbah** [denisraslov/react-spreadsheet-grid#30]
I am getting an extra scrollbars on my page sometimes. I have other components on the top of the page.

![image](https://user-images.githubusercontent.com/206854/60387199-36172c80-9a8f-11e9-8271-529df10669b2.png)

I think this could be solved by letting me set a height property. I could then get the height from something like react-virtualized-auto-sizer and use that.

**Comment by denisraslov** [comment]
Hi @kasbah 

It's available to set a height for the grid right now already. The grid gets the height of a container where it is rendered, so to set the height of the grid, you have to set the height for the container.
