### ISSUE TITLE
Cells need unique key property

### ISSUE THREAD

**Issue by kasbah** [denisraslov/react-spreadsheet-grid#32]
* `react-spreadsheet-grid`:1.4.3
* `React` version: 16.8.2

Running the basic example I get this warning:

```
index.js:1446 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SpreadsheetGrid`. See https://fb.me/react-warning-keys for more information.
    in SpreadsheetRow (created by SpreadsheetGrid)

````

**Comment by denisraslov** [comment]
Hi @kasbah 
You need to use the `getRowKey` prop to define the key getter function for a row component. It seems, that a `getRowKey` function you use returns the same values for different rows. Could you check it?

**Comment by kasbah** [comment]
I was just running the example in the readme. I think the issue is that there is no unique key in the cell components, but unfortunately I don't have time to investigate.

**Comment by denisraslov** [comment]
Thank you, I will check it and try to fix it in the next release.

**Comment by denisraslov** [comment]
Hey @kasbah 

I've finally taken a look, and it seems that (as I wrote above) some of the rows you used in your code have the same `id` prop value, so, as row's key getter function defined as ` getRowKey={row => row.id}`, some rows of the grid get the same keys. Please, change `getRowKey` function or make ids of the rows unique to fix this issue.
