### ISSUE TITLE
Is there a way to make grid to responsive?

### ISSUE THREAD

**Issue by bexoss** [denisraslov/react-spreadsheet-grid#37]
First thanks to open this wonderful library. 
I want to use it my website admin page, and I often to access it with my mobile phone.
What I just want to is a horizontal scrollbar when small screen.

https://www.w3schools.com/howto/howto_css_table_responsive.asp

You can access above url and then test it with small screen, when screen got small, 
it generate a horizontal scrollbar that can see contents easily.
Is there a way to do it?

I tried like 

`<div style={{ overflowX: 'auto}}>
    <Grid ... />
</div>
`

But it seems not working. :)

**Comment by denisraslov** [comment]
Hi @bexoss!
Thanks.

Exactly, a horizontal scrollbar could be done with additional containers for the grid. Please, take a look at an example: https://codesandbox.io/s/friendly-flower-ll74u

**Comment by nkkollaw** [comment]
Otlichnaya rabota, man! Love this lib.

**Comment by denisraslov** [comment]
@nkkollaw Thanks! 🙂
