### ISSUE TITLE
copy value ranges

### ISSUE THREAD

**Issue by kamaldlk** [denisraslov/react-spreadsheet-grid#8]
i'd like to be able copy & paste a range of rows and columns, similar to what you can do in Excel at the moment.

this could be copying between cell ranges on the same grid, between two separate grid instances, or from somewhere off-grid (e.g. Excel).
![3fc45d68-70ca-11e5-907a-38d63878d50a](https://user-images.githubusercontent.com/9652523/33539432-5ff8dee2-d8ec-11e7-817b-6762a9ac3218.gif)

**Comment by denisraslov** [comment]
Hello @kamaldlk!

Thank you, it is an interesting request.
I just have answered the similar question about work with multiple cells in [another issue](https://github.com/denisraslov/react-spreadsheet-grid/issues/9). So, welcome there if you still have questions after you read that issue.
